### ISSUE TITLE
Add demo pages

### ISSUE THREAD

**Issue by youngpilot** [jgonyea/grav-theme-editorial#1]
Hi Jeremy! I love your Editorial Grav Port! It is exactly what I was looking for. I still have issues with showing blogposts in the correct manner. Do you use the theme yourself & could supply some demo pages? That would help me a lot!

All the best from Germany
Julian

**Comment by jgonyea** [comment]
Hi @youngpilot.  Can you elaborate more on the blogposts not showing in correct order?  This is my first grav theme, so thanks for your patience!

**Comment by youngpilot** [comment]
Its not about the order. I cant find a blog.twig file and cannot show blog pages at all. Do you have demo pages? tia

**Comment by jgonyea** [comment]
Hmm, seems like I didn't make one, just a default template.  I'll work on it and get back to you, @youngpilot

**Comment by jgonyea** [comment]
There is now a blog twig file in the latest release.
