### ISSUE TITLE
Cannot change typefaces

### ISSUE THREAD

**Issue by vitaminjosh** [jgonyea/grav-theme-editorial#3]
Using a SASS compiler, and changing any of the font families in _typography.scss in sass -> base doesn't actually change of the typefaces in the theme. Also can't find where the original values: "_font(family)" is being controlled. I might just be missing something simple here, but it would be great to be able to change any of the typefaces in this file.

**Comment by jgonyea** [comment]
Thanks, I'll take a look, @vitamanjosh

**Comment by jgonyea** [comment]
Try changing the values in _vars.scss within libs and see if that helps.

**Comment by jgonyea** [comment]
Hi @vitaminjosh , any luck?

**Comment by jgonyea** [comment]
Closing due to non-response.  I'll reopen if more information arrives.
