### ISSUE TITLE
Github info in theme is incorrect

### ISSUE THREAD

**Issue by awrog** [jgonyea/grav-theme-editorial#7]
Installed 0.1.3
Github info is incorrect:
![screenshot - 3_14_2018 1_23_36 pm](https://user-images.githubusercontent.com/12153667/37402211-f6305402-278a-11e8-857d-db1653ad44d7.png)

https://github.com/jeremy-gonyea/grav-theme-editorial

should read

https://github.com/jgonyea/grav-theme-editorial/

**Comment by jgonyea** [comment]
Oops! Good catch. Thanks.

**Comment by jgonyea** [comment]
Fixed in github.com. Will roll out next release

**Comment by jgonyea** [comment]
Fixed in 1.0.0
