### ISSUE TITLE
Page Collections?

### ISSUE THREAD

**Issue by oscon** [jgonyea/grav-theme-editorial#9]
First of all, cool theme!

Is there a way to use GRAV Page Collections with this theme?
Although there is a template "Blog", but how to properly build a GRAV blog with this theme? Idea: Page Collection and Pagination

...and then:
In what format must the images be, to see them (under Featured) in the sitebar and in a blog entry?
(no pictures (medias!) are displayed within the same folder ...)

**Comment by jgonyea** [comment]
Creating a `blog` page-type, and then creating `item` page types underneath will generate a blog 

(as of v1.0.0 of this theme)
